language: c
script: "./bootstrap && ./configure --with-gmetad --without-php --with-perl=/usr --enable-status --with-memcached && make all"
before_script:
  - sudo apt-get install -y libapr1-dev libconfuse-dev libexpat1-dev libpcre3-dev libssl-dev librrd-dev libperl-dev libmemcache-dev libtool m4 gperf
